version: '3.8'

services:
  # PostgreSQL Database for User Service
  user-db:
    image: postgres:15
    container_name: user-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${USER_DB_PORT}:5432
    volumes:
      - ./.data/user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # PostgreSQL Database for Music Service
  music-db:
    image: postgres:15
    container_name: music-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${MUSIC_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${MUSIC_DB_PORT}:5432
    volumes:
      - ./.data/music-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    command: mvn spring-boot:run
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${USER_PORT}
    ports:
      - ${USER_PORT}:${USER_PORT}
    volumes:
      - ./user-service/src:/app/src
      - ./user-service/test:/app/test
      - ./user-service/mvnw:/app/mvnw
      - ./user-service/mvnw.cmd:/app/mvnw.cmd
      - ./user-service/pom.xml:/app/pom.xml
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - app-network

  # Music Service
  # music-service:
  #   build: ./music-service
  #   container_name: music-service
  #   env_file:
  #     - .env
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://music-db:5432/${MUSIC_DB_NAME}
  #     SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
  #     SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  #     SERVER_PORT: ${MUSIC_PORT}
  #   ports:
  #     - ${MUSIC_PORT}:${MUSIC_PORT}
  #   volumes:
  #     - ./music-service:/app
  #   depends_on:
  #     music-db:
  #       condition: service_healthy
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
