spring.config.import=optional:file:../.env[.properties]
# Server Configuration
server.port=${USER_PORT}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# spring.datasource.url=jdbc:postgresql://localhost:5433/user_db
# spring.datasource.username=postgres
# spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries (optional for debugging)
spring.jpa.show-sql=true

# Logging Level
logging.level.org.springframework=INFO